/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.AutoPartServices;
import Domain.AutoPart;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.OutputStream;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author RALP
 */
public class AddAutoPartFrame extends javax.swing.JFrame {

    /**
     * Creates new form AddAutoPartFrame
     */
    
    private final JFileChooser fc = new JFileChooser();
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField CarBrandTextField;
    private javax.swing.JLabel CarBrandjLabel;
    private javax.swing.JTextField CarModelTextField;
    private javax.swing.JLabel CarModeljLabel;
    private javax.swing.JTextField CostTextField;
    private javax.swing.JLabel CostjLabel;
    private javax.swing.JLabel Label1;
    private javax.swing.JTextField PartImgTextField;
    private javax.swing.JLabel PartImgjLabel;
    private javax.swing.JLabel PartNameLabel;
    private javax.swing.JTextField PartNameTextField;
    private javax.swing.JLabel PartNum;
    private javax.swing.JTextField PartNumTextField;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JLabel PricejLabel;
    private javax.swing.JTextField QuantityTextField;
    private javax.swing.JLabel QuantityjLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton jButton1;

    public AddAutoPartFrame(){
        super("Add AutoPart");
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        SaveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AutoPart a;
                try{

                    if(CarBrandTextField.getText().isEmpty() || CarModelTextField.getText().isEmpty()
                        || CostTextField.getText().isEmpty() || PartImgTextField.getText().isEmpty()
                        || PartNameTextField.getText().isEmpty() ||  PartNumTextField.getText().isEmpty()
                        || PriceTextField.getText().isEmpty() || QuantityTextField.getText().isEmpty()){
                    JOptionPane.showMessageDialog(SaveButton, "Empty Textbox", "Error", JOptionPane.ERROR_MESSAGE);
                }else {
                        String brand = CarBrandTextField.getText();
                        String model = CarModelTextField.getText();
                        Double cost = Double.parseDouble(CostTextField.getText());
                        String img = PartImgTextField.getText();
                        String name = PartNameTextField.getText();
                        String number =PartNumTextField.getText();
                        Double price = Double.parseDouble(PriceTextField.getText());
                        int quantity = Integer.parseInt(QuantityTextField.getText());

                        a = new AutoPart(number, name, model, brand, quantity, cost, price, img);
                        AutoPartServices.createAutoParts(a);

                        AutoPartFrame.update();
                        AddAutoPartFrame.super.dispose();

                    }
                } catch (Exception e1) {
                        JOptionPane.showMessageDialog(SaveButton, "Part Price, Part Cost and Quantiy most be a number", "Error: Invalid Input", JOptionPane.ERROR_MESSAGE);
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PartNumTextField = new javax.swing.JTextField();
        PartNum = new javax.swing.JLabel();
        PartNameLabel = new javax.swing.JLabel();
        PartImgjLabel = new javax.swing.JLabel();
        CarModeljLabel = new javax.swing.JLabel();
        CarBrandjLabel = new javax.swing.JLabel();
        QuantityjLabel = new javax.swing.JLabel();
        CostjLabel = new javax.swing.JLabel();
        PricejLabel = new javax.swing.JLabel();
        PartNameTextField = new javax.swing.JTextField();
        Label1 = new javax.swing.JLabel();
        PartImgTextField = new javax.swing.JTextField();
        CarModelTextField = new javax.swing.JTextField();
        CarBrandTextField = new javax.swing.JTextField();
        QuantityTextField = new javax.swing.JTextField();
        CostTextField = new javax.swing.JTextField();
        PriceTextField = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PartNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PartNumTextFieldActionPerformed(evt);
            }
        });

        PartNum.setText("Parts No.:");

        PartNameLabel.setText("Part Name:");

        PartImgjLabel.setText("Part Image Name:");

        CarModeljLabel.setText("Car Model:");

        CarBrandjLabel.setText("Car Brand:");

        QuantityjLabel.setText("Quantity:");

        CostjLabel.setText("Cost:");

        PricejLabel.setText("Price:");

        Label1.setText("jLabel9");
        Label1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Label1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        CostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CostTextFieldActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        jButton1.setText("...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(SaveButton)
                        .addGap(74, 74, 74)
                        .addComponent(CancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(PartNum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                        .addComponent(PartNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PartNameLabel)
                                            .addComponent(PartImgjLabel)
                                            .addComponent(CarModeljLabel)
                                            .addComponent(CarBrandjLabel)
                                            .addComponent(QuantityjLabel)
                                            .addComponent(CostjLabel)
                                            .addComponent(PricejLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(PartNameTextField)
                                            .addComponent(PartImgTextField)
                                            .addComponent(CarModelTextField)
                                            .addComponent(CarBrandTextField)
                                            .addComponent(QuantityTextField)
                                            .addComponent(CostTextField)
                                            .addComponent(PriceTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(Label1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PartNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PartNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PartNameLabel)
                    .addComponent(PartNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PartImgjLabel)
                    .addComponent(PartImgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarModeljLabel)
                    .addComponent(CarModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarBrandjLabel)
                    .addComponent(CarBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(QuantityjLabel)
                    .addComponent(QuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CostjLabel)
                    .addComponent(CostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PricejLabel)
                    .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(CancelButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PartNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PartNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PartNumTextFieldActionPerformed

    private void Label1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Label1AncestorAdded
     Label1.setVisible(false);
    }//GEN-LAST:event_Label1AncestorAdded

    private void CostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CostTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CostTextFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int returnVal = fc.showOpenDialog(this);
        
        if (returnVal == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            PartImgTextField.setText(file.getPath());
            
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAutoPartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    // End of variables declaration//GEN-END:variables
}
