/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Domain.AutoPart;

import javax.swing.*;

/**
 *
 * @author RALP
 */
public class AutoPartFrame extends javax.swing.JFrame {

    /**
     * Creates new form AutoPartFrame
     */

    private static AddAutoPartFrame addAutoFrame;
    private static ModifyAutoPartFrame modifyFrame;
    //We need to create about frame and help frame

    public AutoPartFrame() {
        super("AutoParts");
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        AddAP = new javax.swing.JMenuItem();
        ModifyAP = new javax.swing.JMenuItem();
        DisplayAP = new javax.swing.JMenuItem();
        APReport = new javax.swing.JMenuItem();
        Quit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        HelpC = new javax.swing.JMenuItem();
        AboutP = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        AddAP.setText("Add Auto Part");
        AddAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAPActionPerformed(evt);
            }
        });
        jMenu1.add(AddAP);

        ModifyAP.setText("Modify Auto Part");
        ModifyAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyAPActionPerformed(evt);
            }
        });
        jMenu1.add(ModifyAP);

        DisplayAP.setText("Display Auto Part");
        jMenu1.add(DisplayAP);

        APReport.setText("Auto Part Report");
        jMenu1.add(APReport);

        Quit.setText("Exit");
        Quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitActionPerformed(evt);
            }
        });
        jMenu1.add(Quit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        HelpC.setText("Help Contents");
        jMenu2.add(HelpC);

        AboutP.setText("About");
        AboutP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutPActionPerformed(evt);
            }
        });
        jMenu2.add(AboutP);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAPActionPerformed
        addAutoFrame = new AddAutoPartFrame();

        addAutoFrame.setVisible(true);
    }//GEN-LAST:event_AddAPActionPerformed

    private void AboutPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutPActionPerformed

    private void ModifyAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyAPActionPerformed
        //Get selected auto part, of search auto part.
        modifyFrame = new ModifyAutoPartFrame(new AutoPart());
        modifyFrame.setVisible(true);
    }//GEN-LAST:event_ModifyAPActionPerformed

    private void QuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitActionPerformed
System.exit(0);
    }//GEN-LAST:event_QuitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoPartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem APReport;
    private javax.swing.JMenuItem AboutP;
    private javax.swing.JMenuItem AddAP;
    private javax.swing.JMenuItem DisplayAP;
    private javax.swing.JMenuItem HelpC;
    private javax.swing.JMenuItem ModifyAP;
    private javax.swing.JMenuItem Quit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
