/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Controllers.AutoPartServices;
import Domain.AutoPart;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 *
 * @author RALP
 */
public class ModifyAutoPartFrame extends javax.swing.JFrame {
    private AutoPart part;
    private final JFileChooser fc = new JFileChooser();
    /**
     * Creates new form ModifyAutoPartFrame
     */
    public ModifyAutoPartFrame(AutoPart p) {
        //System.out.println(p);
        initComponents();


        this.part = p;
        ModCarBrandTextField.setText(part.getCarbrand());
        ModCarModelTextField.setText(part.getCarmodel());
        ModPartImgTextField.setText(part.getImages());
        ModCostTextField.setText(part.getPartcost().toString());
        ModPriceTextField.setText(part.getPartprice().toString());
        ModPartNameTextField.setText(part.getPartname());
        ModQuantityTextField.setText(part.getQuantity().toString());

        ModSaveButton.addActionListener(new ActionListener() {
            /**
             *
             * @param e
             */
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    part.setCarbrand(ModCarBrandTextField.getText());
                    part.setCarmodel(ModCarModelTextField.getText());
                    part.setImages(ModPartImgTextField.getText());
                    part.setPartcost(Double.parseDouble(ModPriceTextField.getText()));
                    part.setPartprice(Double.parseDouble(ModCostTextField.getText()));
                    part.setPartname(ModPartNameTextField.getText());
                    part.setQuantity(Integer.parseInt(ModQuantityTextField.getText()));
                    AutoPartServices.updateAutoParts(part);
                    AutoPartFrame.update();
                    ModifyAutoPartFrame.super.dispose();
                }catch (Exception e1){
                    JOptionPane.showMessageDialog(ModCarBrandjLabel, "Invalid input for Cost, Price or Quantity, most be numbers", "Error", JOptionPane.ERROR_MESSAGE);

                }

            }
        }
    );
        AddimgjButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int returnVal = fc.showOpenDialog(ModifyAutoPartFrame.super.getParent());

                if (returnVal == JFileChooser.APPROVE_OPTION){
                    File file = fc.getSelectedFile();
                    ModPartImgTextField.setText(file.getPath());

                }
            }
        });


    }

    /**
     * Default Constructore
     */
    public ModifyAutoPartFrame(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        ModPartNameLabel = new javax.swing.JLabel();
        ModPartImgjLabel = new javax.swing.JLabel();
        ModCarModeljLabel = new javax.swing.JLabel();
        ModCarBrandjLabel = new javax.swing.JLabel();
        ModQuantityjLabel = new javax.swing.JLabel();
        ModCostjLabel = new javax.swing.JLabel();
        ModPricejLabel = new javax.swing.JLabel();
        ModPartNameTextField = new javax.swing.JTextField();
        ModPartImgTextField = new javax.swing.JTextField();
        ModCarModelTextField = new javax.swing.JTextField();
        ModCarBrandTextField = new javax.swing.JTextField();
        ModQuantityTextField = new javax.swing.JTextField();
        ModCostTextField = new javax.swing.JTextField();
        ModPriceTextField = new javax.swing.JTextField();
        ModSaveButton = new javax.swing.JButton();
        ModCancelButton = new javax.swing.JButton();
        AddimgjButton = new javax.swing.JButton();



        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        setTitle("Modify Auto Part");

        ModPartNameLabel.setText("Part Name:");

        ModPartImgjLabel.setText("Part Image Name:");

        ModCarModeljLabel.setText("Car Model:");

        ModCarBrandjLabel.setText("Car Brand:");

        ModQuantityjLabel.setText("Quantity:");

        ModCostjLabel.setText("Cost:");

        ModPricejLabel.setText("Price:");
        ModPartImgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModPartImgTextFieldActionPerformed(evt);
            }
        });

        ModCarModelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModCarModelTextFieldActionPerformed(evt);
            }
        });

        ModCostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModCostTextFieldActionPerformed(evt);
            }
        });

        ModSaveButton.setText("Save");

        ModCancelButton.setText("Cancel");
        ModCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModCancelButtonActionPerformed(evt);
            }
        });

        AddimgjButton.setText("...");
        AddimgjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddimgjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(ModPartNameLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ModPartNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(ModPartImgjLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ModPartImgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(AddimgjButton))
                                .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                        .addComponent(ModSaveButton)
                                                        .addGap(80, 80, 80)
                                                        .addComponent(ModCancelButton))
                                                .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(ModCostjLabel)
                                                                .addComponent(ModPricejLabel))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(ModPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(ModCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(ModCarModeljLabel)
                                                        .addComponent(ModCarBrandjLabel)
                                                        .addComponent(ModQuantityjLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(ModCarBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ModQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(ModCarModelTextField)
                                                                .addGap(2, 2, 2))))))
                        .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ModPartNameLabel)
                                        .addComponent(ModPartNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ModPartImgjLabel)
                                        .addComponent(ModPartImgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddimgjButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ModCarModelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ModCarModeljLabel))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ModCarBrandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ModCarBrandjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ModQuantityjLabel)
                                        .addComponent(ModQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ModCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ModCostjLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ModPriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ModPricejLabel))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(ModSaveButton)
                                        .addComponent(ModCancelButton))
                                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModCostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModCostTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModCostTextFieldActionPerformed

    private void ModPartImgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModPartImgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModPartImgTextFieldActionPerformed

    private void ModCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModCancelButtonActionPerformed
        super.dispose();
    }//GEN-LAST:event_ModCancelButtonActionPerformed

    private void AddimgjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddimgjButtonActionPerformed

    }//GEN-LAST:event_AddimgjButtonActionPerformed

    private void ModCarModelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModCarModelTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModCarModelTextFieldActionPerformed




    /**
     * Test of the frame without functionality
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyAutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyAutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyAutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyAutoPartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //AutoPart part = new AutoPart();
                new ModifyAutoPartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddimgjButton;
    private javax.swing.JButton ModCancelButton;
    private javax.swing.JTextField ModCarBrandTextField;
    private javax.swing.JLabel ModCarBrandjLabel;
    private javax.swing.JTextField ModCarModelTextField;
    private javax.swing.JLabel ModCarModeljLabel;
    private javax.swing.JTextField ModCostTextField;
    private javax.swing.JLabel ModCostjLabel;
    private javax.swing.JTextField ModPartImgTextField;
    private javax.swing.JLabel ModPartImgjLabel;
    private javax.swing.JLabel ModPartNameLabel;
    private javax.swing.JTextField ModPartNameTextField;
    private javax.swing.JTextField ModPriceTextField;
    private javax.swing.JLabel ModPricejLabel;
    private javax.swing.JTextField ModQuantityTextField;
    private javax.swing.JLabel ModQuantityjLabel;
    private javax.swing.JButton ModSaveButton;
    // End of variables declaration//GEN-END:variables
}
